logging:
    level:
#        tk.mybatis: DEBUG
        com.github.wxiaoqi.gate.back: INFO
  #  config: classpath:logback.xml
    # path: /ag/admin
spring:
    application:
        name: gate-way
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    redis:
        database: 1
        host: 127.0.0.1
        pool:
            max-active: 20
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/ag_gate_way?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.github.wxiaoqi.gate.back.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8762

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
swagger:
    basepackage: com.github.wxiaoqi.gate.back.api
    service:
        name: 网关中心Api
        description: 网关中心鉴权Api
        developer: 老A

gate:
    client:
        authHeader: access-token
        authHost: http://localhost:8762/api/authen
        tokenHead: ApiGateToken
    ignore:
        startWith: /admin,/index,/about
        contain: .
    api:
        header: access-token  #http 请求头key
        secret: mySecret   #jwt 加密密钥
        expiration: 7200  # 过期秒数
        tokenHead: ApiGateToken # 认证token前缀

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    gate-demo-provider:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
zuul:
  prefix: /api #为zuul设置一个公共的前缀
#  host:
#    maxTotalConnections: 1000
#    socket-timeout-millis: 100000
#    connect-timeout-millis: 100000
  semaphore:
    max-semaphores: 1000


ribbon:
  eureka:
    enabled: true

#gate-demo-provider:
#  ribbon:
#    ConnectTimeout: 10000
#    ReadTimeout: 10000
